import { CREAR_CURSO, INCREMENTAR_ID, BORRAR_CURSO, DECREMENTAR_ID, SELECCIONAR_CURSO, DESELECCIONAR_CURSO, EDIT_CURSO, DESELECCIONAR_TODO, INITIAL_STATE_CURSO } from './curso'
import { PUSH_NOTIFICATION, POP_NOTIFICATION, INITIAL_STATE_NOTIFICATION } from './notification'
import { SETUP_TOTALS } from './totals'

export default {
  curso: {
    INITIAL_STATE_CURSO,
    CREAR_CURSO,
    INCREMENTAR_ID,
    BORRAR_CURSO,
    SELECCIONAR_CURSO,
    DECREMENTAR_ID,
    DESELECCIONAR_CURSO,
    EDIT_CURSO,
    DESELECCIONAR_TODO
  },
  notification: {
    INITIAL_STATE_NOTIFICATION,
    PUSH_NOTIFICATION,
    POP_NOTIFICATION
  },
  totals: {
    SETUP_TOTALS
  }
}
