import { CREAR_CURSO, INCREMENTAR_ID, BORRAR_CURSO, DECREMENTAR_ID, SELECCIONAR_CURSO, DESELECCIONAR_CURSO, EDIT_CURSO, DESELECCIONAR_TODO, INITIAL_STATE_CURSO } from './curso'
import { PUSH_NOTIFICATION, POP_NOTIFICATION, INITIAL_STATE_NOTIFICATION } from './notification'

export default {
  CREAR_CURSO,
  INCREMENTAR_ID,
  BORRAR_CURSO,
  SELECCIONAR_CURSO,
  DECREMENTAR_ID,
  PUSH_NOTIFICATION,
  POP_NOTIFICATION,
  DESELECCIONAR_CURSO,
  EDIT_CURSO,
  DESELECCIONAR_TODO,
  INITIAL_STATE_CURSO,
  INITIAL_STATE_NOTIFICATION
}
